(function(g){var window=this;var Z5=function(a,b,c){a.w.set(b,c)},$5=function(a){Z5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.H)()).toString(36));
return a},a6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.Gm(a.w,b,c)},Cua=function(a,b){var c=[];
g.Pj(b,function(d){try{var e=g.Jn.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.In(e)&&c.push(d)},a);
return c},Dua=function(a,b){var c=Cua(a,b);
(0,g.y)(c,function(d){g.Jn.prototype.remove.call(this,d)},a)},Eua=function(a){if(a.Yc){if(a.Yc.locationOverrideToken)return{locationOverrideToken:a.Yc.locationOverrideToken};
if(null!=a.Yc.latitudeE7&&null!=a.Yc.longitudeE7)return{latitudeE7:a.Yc.latitudeE7,longitudeE7:a.Yc.longitudeE7}}return null},Fua=function(a,b){g.bb(a,b)||a.push(b)},Gua=function(a,b){var c=b instanceof g.Zb?b:g.dc(b,/^data:image\//i.test(b));
a.src=g.$b(c)},b6=function(){},Hua=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Iua=function(a,b,c,d){var e=new g.vm(null,void 0);
a&&g.wm(e,a);b&&g.xm(e,b);c&&g.ym(e,c);d&&(e.u=d);return e},c6=function(a,b){g.vo[a]=!0;
var c=g.to();c&&c.publish.apply(c,arguments);g.vo[a]=!1},d6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.w=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.rm;this.o=this.u="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Jua(this,a.capabilities||""),Kua(this,a.experiments||""),this.u=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},Jua=function(a,b){a.capabilities.clear();
(0,g.be)(b.split(","),g.Sa(g.A.contains,Lua)).forEach(function(c){a.capabilities.add(c)})},Kua=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},e6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},f6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},Mua=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Nua=function(a){return new e6(a)},Oua=function(a){return g.Ma(a)?(0,g.ic)(a,Nua):[]},g6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},h6=function(a){return g.Ma(a)?"["+(0,g.ic)(a,g6).join(",")+"]":"null"},i6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Pua=function(a){return(0,g.ic)(a,function(b){return{key:b.id,
name:b.name}})},j6=function(a,b){return g.Za(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},k6=function(a,b){return g.Za(a,function(c){return f6(c,b)})},l6=function(a){try{var b=(0,g.Vr)(),c=(0,g.Ur)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},Qua=function(){var a=(0,g.Ur)();
a&&Dua(a,a.o.mf(!0))},m6=function(){var a=g.Xr("yt-remote-connected-devices")||[];
g.sb(a);return a},Rua=function(a){if(g.cb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.ic)(a,function(d,e){return 0==e?d:d.substring(c.length)})},Sua=function(a){g.Wr("yt-remote-connected-devices",a,86400)},o6=function(){if(n6)return n6;
var a=g.Xr("yt-remote-device-id");a||(a=i6(),g.Wr("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.bb(b,d);)c++,d=a+"#"+c;return n6=d},p6=function(){var a=m6(),b=o6();
g.bb(a,b);g.Yr()&&g.ub(a,b);a=Rua(a);if(g.cb(a))try{g.jq("remote_sid")}catch(c){}else try{g.hq("remote_sid",a.join(","),-1)}catch(c){}},Tua=function(){return g.Xr("yt-remote-session-browser-channel")},Uua=function(){return g.Xr("yt-remote-local-screens")||[]},Vua=function(){g.Wr("yt-remote-lounge-token-expiration",!0,86400)},Wua=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.ic)(Uua(),function(d){return d.loungeToken}),c=(0,g.ic)(a,function(d){return d.loungeToken});
(0,g.ai)(c,function(d){return!g.bb(b,d)})&&Vua();
g.Wr("yt-remote-local-screens",a,31536E3)},Xua=function(a,b){g.Wr("yt-remote-session-browser-channel",a);
g.Wr("yt-remote-session-screen-id",b);var c=m6(),d=o6();g.bb(c,d)||c.push(d);Sua(c);p6()},q6=function(a){a||(l6("yt-remote-session-screen-id"),l6("yt-remote-session-video-id"));
p6();a=m6();g.fb(a,o6());Sua(a)},Yua=function(){if(!r6){var a=g.Un();
a&&(r6=new g.Dn(a))}return r6?!!r6.get("yt-remote-use-staging-server"):!1},Zua=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},$ua=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s6=function(a){a.length?ava(a.shift(),function(){s6(a)}):t6()},bva=function(a){return"chrome-extension://"+a+"/cast_sender.js"},ava=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},t6=function(){var a=$ua();
a&&a(!1,"No cast extension found")},dva=function(){if(cva){var a=2,b=$ua(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;ava("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t6,c)}},eva=function(){dva();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);s6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},u6=function(a,b,c){g.B.call(this);
this.C=null!=c?(0,g.x)(a,c):a;this.Gd=b;this.B=(0,g.x)(this.rF,this);this.o=!1;this.u=0;this.w=this.Ea=null;this.A=[]},v6=function(a,b,c){g.B.call(this);
this.w=null!=c?(0,g.x)(a,c):a;this.Gd=b;this.u=(0,g.x)(this.sF,this);this.o=[]},w6=function(a){a.Ea=g.zf(a.u,a.Gd);
a.w.apply(null,a.o)},x6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return Hua(a)},y6=function(){},z6=function(){},fva=function(){},hva=function(a){return(a=gva(a))?new ActiveXObject(a):new XMLHttpRequest},gva=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},A6=function(a,b,c,d){this.o=a;
this.w=b;this.G=c;this.F=d||1;this.B=45E3;this.A=new g.N1(this);this.u=new g.yf;this.u.setInterval(250)},jva=function(a,b,c){a.wj=1;
a.Sg=$5(b.clone());a.Ni=c;a.C=!0;iva(a,null)},B6=function(a,b,c,d,e){a.wj=1;
a.Sg=$5(b.clone());a.Ni=null;a.C=c;e&&(a.TB=!1);iva(a,d)},iva=function(a,b){a.fk=(0,g.H)();
C6(a);a.Eh=a.Sg.clone();a6(a.Eh,"t",a.F);a.Qm=0;a.Oc=a.o.ir(a.o.Em()?b:null);0<a.Ur&&(a.Ip=new v6((0,g.x)(a.RC,a,a.Oc),a.Ur));a.A.ka(a.Oc,"readystatechange",a.iO);var c=a.oi?g.A.clone(a.oi):{};a.Ni?(a.qq="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Oc.send(a.Eh,a.qq,a.Ni,c)):(a.qq="GET",a.TB&&!g.Qd&&(c.Connection="close"),a.Oc.send(a.Eh,a.qq,null,c));a.o.cf(1)},mva=function(a,b,c){for(var d=!0;!a.Vh&&a.Qm<c.length;){var e=kva(a,c);
if(e==D6){4==b&&(a.hh=4,E6(15),d=!1);break}else if(e==lva){a.hh=4;E6(16);d=!1;break}else F6(a,e)}4==b&&0==c.length&&(a.hh=1,E6(17),d=!1);a.ff=a.ff&&d;d||(G6(a),H6(a))},kva=function(a,b){var c=a.Qm,d=b.indexOf("\n",c);
if(-1==d)return D6;c=Number(b.substring(c,d));if(isNaN(c))return lva;d+=1;if(d+c>b.length)return D6;var e=b.substr(d,c);a.Qm=d+c;return e},ova=function(a,b){a.fk=(0,g.H)();
C6(a);var c=b?window.location.hostname:"";a.Eh=a.Sg.clone();Z5(a.Eh,"DOMAIN",c);Z5(a.Eh,"t",a.F);try{a.kf=new ActiveXObject("htmlfile")}catch(n){G6(a);a.hh=7;E6(22);H6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in I6)k=I6[l];else if(l in nva)k=I6[l]=nva[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
I6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Cc(g.Eb("b/12014412"),d+"</body></html>");a.kf.open();a.kf.write(g.xc(c));a.kf.close();a.kf.parentWindow.m=(0,g.x)(a.DN,a);a.kf.parentWindow.d=(0,g.x)(a.aB,a,!0);a.kf.parentWindow.rpcClose=(0,g.x)(a.aB,a,!1);c=a.kf.createElement("DIV");a.kf.parentWindow.document.body.appendChild(c);d=g.cc(a.Eh.toString());d=g.Lc(g.$b(d));d=g.Cc(g.Eb("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Dc(c,d);a.o.cf(1)},C6=function(a){a.Yu=(0,g.H)()+a.B;
pva(a,a.B)},pva=function(a,b){if(null!=a.xk)throw Error("WatchDog timer not null");
a.xk=J6((0,g.x)(a.LN,a),b)},K6=function(a){a.xk&&(g.v.clearTimeout(a.xk),a.xk=null)},H6=function(a){a.o.Gx()||a.Vh||a.o.wp(a)},G6=function(a){K6(a);
g.ne(a.Ip);a.Ip=null;a.u.stop();g.Cpa(a.A);if(a.Oc){var b=a.Oc;a.Oc=null;b.abort();b.dispose()}a.kf&&(a.kf=null)},F6=function(a,b){try{a.o.UA(a,b),a.o.cf(4)}catch(c){}},rva=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;qva(a,b,function(k){k?c(!0):g.v.setTimeout(function(){rva(a,b,c,d,f)},f)})}},qva=function(a,b,c){var d=new Image;
d.onload=function(){try{L6(d),c(!0)}catch(e){}};
d.onerror=function(){try{L6(d),c(!1)}catch(e){}};
d.onabort=function(){try{L6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{L6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
Gua(d,a)},L6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},sva=function(a){this.o=a;
this.u=new y6},tva=function(a){var b=M6(a.o,a.Fk,"/mail/images/cleardot.gif");
$5(b);rva(b.toString(),5E3,(0,g.x)(a.mE,a),3,2E3);a.cf(1)},O6=function(a){var b=a.o.H;
if(null!=b)E6(5),b?(E6(11),N6(a.o,a,!1)):(E6(12),N6(a.o,a,!0));else if(a.ae=new A6(a,void 0,void 0,void 0),a.ae.oi=a.Sr,b=a.o,b=M6(b,b.Em()?a.kl:null,a.Tr),E6(5),!g.Od||g.sd(10))a6(b,"TYPE","xmlhttp"),B6(a.ae,b,!1,a.kl,!1);else{a6(b,"TYPE","html");var c=a.ae;a=!!a.kl;c.wj=3;c.Sg=$5(b.clone());ova(c,a)}},P6=function(a){g.Ne.call(this);
this.headers=new g.rm;this.R=a||null;this.w=!1;this.V=this.o=null;this.da=this.H="";this.C=0;this.A="";this.B=this.aa=this.G=this.T=!1;this.F=0;this.J=null;this.ea="";this.M=this.Z=!1},uva=function(a){return g.Od&&g.rd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},vva=function(a){return"content-type"==a.toLowerCase()},xva=function(a,b){a.w=!1;
a.o&&(a.B=!0,a.o.abort(),a.B=!1);a.A=b;a.C=5;wva(a);Q6(a)},wva=function(a){a.T||(a.T=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},zva=function(a){if(a.w&&"undefined"!=typeof g.S1)if(a.V[1]&&4==R6(a)&&2==a.getStatus())S6(a,"Local request error detected and ignored");
else if(a.G&&4==R6(a))g.zf(a.QA,0,a);else if(a.dispatchEvent("readystatechange"),4==R6(a)){S6(a,"Request complete");a.w=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Vc(1,String(a.H));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!yva.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.C=6;try{var l=2<R6(a)?a.o.statusText:""}catch(m){l=""}a.A=l+" ["+a.getStatus()+"]";wva(a)}}finally{Q6(a)}}},Q6=function(a,b){if(a.o){Ava(a);
var c=a.o,d=a.V[0]?g.Ja:null;a.o=null;a.V=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},Ava=function(a){a.o&&a.M&&(a.o.ontimeout=null);
a.J&&(g.v.clearTimeout(a.J),a.J=null)},R6=function(a){return a.o?a.o.readyState:0},T6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},S6=function(a,b){return b+" ["+a.da+" "+a.H+" "+a.getStatus()+"]"},U6=function(a,b,c){this.o=1;
this.u=[];this.A=[];this.B=new y6;this.G=a||null;this.H=null!=b?b:null;this.C=c||!1},Bva=function(a,b){this.o=a;
this.map=b;this.context=null},Cva=function(a){g.pe.call(this,"statevent",a)},Dva=function(a,b){g.pe.call(this,"timingevent",a);
this.size=b},Eva=function(a){g.pe.call(this,"serverreachability",a)},Hva=function(a){Fva(a);
if(3==a.o){var b=a.cm++,c=a.Zn.clone();Z5(c,"SID",a.w);Z5(c,"RID",b);Z5(c,"TYPE","terminate");V6(a,c);b=new A6(a,a.w,b,void 0);b.wj=2;b.Sg=$5(c.clone());Gua(new Image,b.Sg.toString());b.fk=(0,g.H)();C6(b)}Gva(a)},Iva=function(a){a.LE(1,0);
a.Zn=M6(a,null,a.Rr);W6(a)},Fva=function(a){a.Wg&&(a.Wg.abort(),a.Wg=null);
a.sc&&(a.sc.cancel(),a.sc=null);a.Wf&&(g.v.clearTimeout(a.Wf),a.Wf=null);X6(a);a.Sd&&(a.Sd.cancel(),a.Sd=null);a.bh&&(g.v.clearTimeout(a.bh),a.bh=null)},Jva=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new Bva(a.TJ++,b));2!=a.o&&3!=a.o||W6(a)},W6=function(a){a.Sd||a.bh||(a.bh=J6((0,g.x)(a.ZA,a),0),a.pj=0)},Lva=function(a,b){if(1==a.o){if(!b){a.cm=Math.floor(1E5*Math.random());
var c=a.cm++,d=new A6(a,"",c,void 0);d.oi=null;var e=Y6(a),f=a.Zn.clone();Z5(f,"RID",c);Z5(f,"CVER","1");V6(a,f);jva(d,f,e);a.Sd=d;a.o=2}}else 3==a.o&&(b?Kva(a,b):0==a.u.length||a.Sd||Kva(a))},Kva=function(a,b){if(b)if(6<a.Wh){a.u=a.A.concat(a.u);
a.A.length=0;var c=a.cm-1;var d=Y6(a)}else c=b.G,d=b.Ni;else c=a.cm++,d=Y6(a);var e=a.Zn.clone();Z5(e,"SID",a.w);Z5(e,"RID",c);Z5(e,"AID",a.Ij);V6(a,e);c=new A6(a,a.w,c,a.pj+1);c.oi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Sd=c;jva(c,e,d)},V6=function(a,b){if(a.Cd){var c=a.Cd.dx();
c&&g.A.forEach(c,function(d,e){Z5(b,e,d)})}},Y6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.Wh&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,k=a.u[e].map;f=6>=a.Wh?e:f-d;try{g.A.forEach(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.A=a.A.concat(a.u.splice(0,b));
return c.join("&")},Mva=function(a){a.sc||a.Wf||(a.F=1,a.Wf=J6((0,g.x)(a.YA,a),0),a.fj=0)},Z6=function(a){if(a.sc||a.Wf||3<=a.fj)return!1;
a.F++;a.Wf=J6((0,g.x)(a.YA,a),Nva(a,a.fj));a.fj++;return!0},N6=function(a,b,c){a.nq=c;
a.wf=b.mg;a.C||Iva(a)},X6=function(a){null!=a.di&&(g.v.clearTimeout(a.di),a.di=null)},Nva=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},$6=function(a,b){if(2==b||9==b){var c=null;
a.Cd&&(c=null);var d=(0,g.x)(a.UO,a);c||(c=new g.vm("//www.google.com/images/cleardot.gif"),$5(c));qva(c.toString(),1E4,d)}else E6(2);Ova(a,b)},Ova=function(a,b){a.o=0;
a.Cd&&a.Cd.rw(b);Gva(a);Fva(a)},Gva=function(a){a.o=0;
a.wf=-1;if(a.Cd)if(0==a.A.length&&0==a.u.length)a.Cd.ar();else{g.jb(a.A);var b=g.jb(a.u);a.A.length=0;a.u.length=0;a.Cd.ar(b)}},M6=function(a,b,c){var d=g.Dm(c);
if(""!=d.o)b&&g.xm(d,b+"."+d.o),g.ym(d,d.A);else{var e=window.location;d=Iua(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Tk&&g.A.forEach(a.Tk,function(f,k){Z5(d,k,f)});
Z5(d,"VER",a.Wh);V6(a,d);return d},J6=function(a,b){if(!g.Oa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},E6=function(a){a7.dispatchEvent(new Cva(a7,a))},Pva=function(){},Qva=function(){this.o=[];
this.u=[]},Rva=function(a,b){this.action=a;
this.params=b||{}},b7=function(a,b){g.B.call(this);
this.o=new g.I(this.uN,0,this);g.C(this,this.o);this.Gd=5E3;this.u=0;if(g.Oa(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Oa(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.w=a},c7=function(a,b,c){this.J=a;
this.C=b;this.w=new g.Cn;this.u=new b7(this.xO,this);this.o=null;this.vb=!1;this.B=null;this.H="";this.G=this.A=0;this.F=[];this.M=c||!1},Sva=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.nq,sessionId:a.o.w,arrayId:a.o.Ij}},Tva=function(a,b){a.G=b||0;
a.u.stop();a.o&&(3==a.o.o&&Lva(a.o),Hva(a.o));a.G=0},d7=function(a){return!!a.o&&3==a.o.o},Uva=function(a,b){(a.C.loungeIdToken=b)||a.u.stop()},e7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.Vc(4,a))||"";b&&(this.port=":"+b);this.domain=g.Wc(a)||"";a=g.oc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Wb(a,"10.0")&&(this.u=!1))},f7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.fd(c+b,{})},g7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Sa(a.A,d,!0),onError:g.Sa(a.w,e),Yd:g.Sa(a.B,e)};c&&(a.ub=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.$p(b,a)},Yva=function(){var a=Vva;
Wva();h7.push(a);Xva(h7)},i7=function(a,b){Wva();
var c=h7,d=Zva(a,String(b));g.cb(c)?$va(d):(Xva(c),(0,g.y)(c,function(e){e(d)}))},Wva=function(){h7||(h7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ia("yt.mdx.remote.debug.handlers_",h7,void 0))},$va=function(a){var b=(j7+1)%50;
j7=b;k7[b]=a;l7||(l7=49==b)},Xva=function(a){var b=k7;
if(b[0]){var c=j7,d=l7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
k7=Array(50);j7=-1;l7=!1}},Zva=function(a,b){var c=((0,g.H)()-awa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},m7=function(a){g.Q.call(this);
this.F=a;this.o=[]},bwa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},cwa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.be)(a.o,function(f){return!!j6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=bwa(a,b[d])||c;return c},dwa=function(a,b){var c=a.o.length;
a.o=(0,g.be)(a.o,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.o.length<c},n7=function(a,b,c,d){g.Q.call(this);
this.C=a;this.A=b;this.B=c;this.w=d;this.u=0;this.o=null;this.Ea=NaN},p7=function(a){m7.call(this,"LocalScreenService");
this.w=a;this.u=NaN;o7(this);this.info("Initializing with "+h6(this.o))},ewa=function(a){if(a.o.length){var b=(0,g.ic)(a.o,function(d){return d.id}),c=f7(a.w,"/pairing/get_lounge_token_batch");
g7(a.w,c,{screen_ids:b.join(",")},(0,g.x)(a.CF,a),(0,g.x)(a.BF,a))}},o7=function(a){var b=Oua(Uua());
b=(0,g.be)(b,function(c){return!c.uuid});
return cwa(a,b)},q7=function(a,b){Wua((0,g.ic)(a.o,Mua));
b&&Vua()},s7=function(a,b){g.Q.call(this);
this.C=b;var c=g.Xr("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.bb(c,l)}this.o=d;this.B=a;this.w=this.A=NaN;this.u=null;r7("Initialized with "+g.rk(this.o))},fwa=function(a,b,c){var d=f7(a.B,"/pairing/get_screen_availability");
g7(a.B,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},t7=function(a,b){a:if(g.A.Sc(b)!=g.A.Sc(a.o))var c=!1;
else{c=g.A.Gb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(r7("Updated online screens: "+g.rk(a.o)),a.o=b,a.P("screenChange"));gwa(a)},u7=function(a){isNaN(a.w)||g.so(a.w);
a.w=g.qo((0,g.x)(a.ou,a),0<a.A&&a.A<(0,g.H)()?2E4:1E4)},r7=function(a){i7("OnlineScreenService",a)},hwa=function(a){var b={};
(0,g.y)(a.C(),function(c){c.token?b[c.token]=c.id:this.Tb("Requesting availability of screen w/o lounge token.")});
return b},gwa=function(a){a=g.A.Gb(g.A.filter(a.o,function(b){return b}));
g.sb(a);a.length?g.Wr("yt-remote-online-screen-ids",a.join(","),60):l6("yt-remote-online-screen-ids")},v7=function(a){m7.call(this,"ScreenService");
this.C=a;this.u=this.w=null;this.A=[];this.B={};iwa(this)},kwa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.oe();if(k=(c?k6(k,c):null)||k6(k,b)){k.uuid=b;var l=w7(a,k);fwa(a.u,l,function(m){e(m?l:null)})}else c?jwa(a,c,(0,g.x)(function(m){var n=w7(this,new e6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));fwa(this.u,n,function(p){e(p?n:null)})},a),f):e(null)},lwa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},jwa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={ub:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.$p(f7(a.C,"/pairing/get_lounge_token_batch"),e)},mwa=function(a){a.o=a.w.oe();
for(var b=g.A.sC(a.B),c=0,d=a.o.length;c<d;++c){var e=a.o[c];e.uuid=b[e.id]||""}a.info("Updated manual screens: "+h6(a.o))},iwa=function(a){x7(a);
a.w=new p7(a.C);a.w.subscribe("screenChange",(0,g.x)(a.LF,a));mwa(a);a.A=Oua(g.Xr("yt-remote-automatic-screen-cache")||[]);x7(a);a.info("Initializing automatic screens: "+h6(a.A));a.u=new s7(a.C,(0,g.x)(a.oe,a,!0));a.u.subscribe("screenChange",(0,g.x)(function(){this.P("onlineScreenChange")},a))},w7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=k6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.Wr("yt-remote-automatic-screen-cache",(0,g.ic)(a.A,Mua)));x7(a);a.B[b.uuid]=b.id;g.Wr("yt-remote-device-id-map",a.B,31536E3);return b},x7=function(a){a.B=g.Xr("yt-remote-device-id-map")||{}},y7=function(a,b,c){g.Q.call(this);
this.V=c;this.H=a;this.u=b;this.w=null},z7=function(a,b){i7(a.V,b)},A7=function(a,b){y7.call(this,a,b,"CastSession");
this.o=null;this.A=0;this.C=(0,g.x)(this.DP,this);this.B=(0,g.x)(this.TN,this);this.A=g.qo((0,g.x)(function(){nwa(this,null)},this),12E4)},owa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.rk(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ja,(0,g.x)(function(){z7(this,"Failed to send message: getMdxSessionStatus.")},a)):z7(a,"Sending yt message without session: "+g.rk(b))},nwa=function(a,b){g.so(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.w||a.w.id!=b){var c=(0,g.x)(a.yp,a),d=(0,g.x)(a.re,a);a.zx(b,c,d,5)}}else a.re(Error("Waiting for session status timed out."))},B7=function(a,b,c){y7.call(this,a,b,"DialSession");
this.A=this.G=null;this.J="";this.R=c;this.B=null;this.F=g.Ja;this.C=NaN;this.M=(0,g.x)(this.GP,this);this.o=g.Ja},pwa=function(a){a.o=a.H.YC(a.J,a.u.label,a.u.friendlyName,(0,g.x)(function(b){this.o=g.Ja;
this.yp(b)},a),(0,g.x)(function(b){this.o=g.Ja;
this.re(b)},a))},qwa=function(a){var b={};
b.pairingCode=a.J;b.theme=a.R;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}Yua()&&(b.env_useStageMdx=1);return g.dd(b)},C7=function(a,b){y7.call(this,a,b,"ManualSession");
this.o=g.qo((0,g.x)(this.Jj,this,null),150)},D7=function(a,b,c,d){g.Q.call(this);
this.u=a;this.F=b||"233637DE";this.C=c||"cl";this.G=d||!1;this.o=null;this.B=!1;this.w=[];this.A=(0,g.x)(this.BM,this)},rwa=function(a,b){return b?g.Za(a.w,function(c){return f6(b,c.label)},a):null},E7=function(a){i7("Controller",a)},Vva=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},F7=function(a){return a.B||!!a.w.length||!!a.o},G7=function(a,b,c){b!=a.o&&(g.ne(a.o),(a.o=b)?(c?a.P("yt-remote-cast2-receiver-resumed",b.u):a.P("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.x)(a.XA,a,b)),b.w?a.P("yt-remote-cast2-session-change",b.w):c&&a.o.Jj(null)):a.P("yt-remote-cast2-session-change",null))},swa=function(a){var b=a.u.XC(),c=a.o&&a.o.u;
a=(0,g.ic)(b,function(d){c&&f6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=rwa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},ywa=function(a,b,c,d,e,f,k){twa()?uwa(b,e,f,k)&&(I7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?vwa(a,c):(window.__onGCastApiAvailable=function(l,m){l?vwa(a,c):(J7("Failed to load cast API: "+m),K7(!1),I7(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),wwa(),c(!1))},d?g.Co("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?eva():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?t6():(dva(),s6(xwa.map(bva))))):H7("Cannot initialize because not running Chrome")},wwa=function(){H7("dispose");
var a=L7();a&&a.dispose();g.Ia("yt.mdx.remote.cloudview.instance_",null,void 0);zwa(!1);g.yo(M7);M7.length=0},N7=function(){return!!g.Xr("yt-remote-cast-installed")},Awa=function(){var a=g.Xr("yt-remote-cast-receiver");
return a?a.friendlyName:null},Bwa=function(){H7("clearCurrentReceiver");
l6("yt-remote-cast-receiver")},Cwa=function(){return N7()?L7()?L7().getCastSession():(J7("getCastSelector: Cast is not initialized."),null):(J7("getCastSelector: Cast API is not installed!"),null)},P7=function(){N7()?L7()?O7()?(H7("Requesting cast selector."),L7().requestSession()):(H7("Wait for cast API to be ready to request the session."),M7.push(g.xo("yt-remote-cast2-api-ready",P7))):J7("requestCastSelector: Cast is not initialized."):J7("requestCastSelector: Cast API is not installed!")},Q7=
function(a,b){O7()?L7().setConnectedScreenStatus(a,b):J7("setConnectedScreenStatus called before ready.")},twa=function(){var a=0<=g.oc.search(/ (CrMo|Chrome|CriOS)\//);
return g.Qs||a},Dwa=function(a,b){L7().init(a,b)},uwa=function(a,b,c,d){var e=!1;
L7()||(a=new D7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Wr("yt-remote-cast-available",f);c6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){H7("onReceiverSelected: "+f.friendlyName);
g.Wr("yt-remote-cast-receiver",f);c6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){H7("onReceiverResumed: "+f.friendlyName);
g.Wr("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){H7("onSessionChange: "+g6(f));
f||l6("yt-remote-cast-receiver");c6("yt-remote-cast2-session-change",f)}),g.Ia("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
H7("cloudview.createSingleton_: "+e);return e},L7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},vwa=function(a,b){K7(!0);
I7(!1);Dwa(a,function(c){c?(zwa(!0),g.zo("yt-remote-cast2-api-ready")):(J7("Failed to initialize cast API."),K7(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),wwa());b(c)})},H7=function(a){i7("cloudview",a)},J7=function(a){i7("cloudview",a)},K7=function(a){H7("setCastInstalled_ "+a);
g.Wr("yt-remote-cast-installed",a)},O7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},zwa=function(a){H7("setApiReady_ "+a);
g.Ia("yt.mdx.remote.cloudview.apiReady_",a,void 0)},I7=function(a){g.Ia("yt.mdx.remote.cloudview.initializing_",a,void 0)},R7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.C=this.F=0;this.o=null;this.hasNext=this.J=!1;this.H=this.G=this.u=this.B=0;this.A=NaN;this.w=!1;this.reset(a)},S7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.J=!1;a.hasNext=!1;a.F=0;a.C=(0,g.H)();a.B=0;a.u=0;a.G=0;a.H=0;a.A=NaN;a.w=!1},T7=function(a){return a.ab()?((0,g.H)()-a.C)/1E3:0},U7=function(a,b){a.F=b;
a.C=(0,g.H)()},V7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.C)/1E3+a.F;
case -1E3:return 0}return a.F},W7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&S7(a)},X7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.A.Nm(a.o);b.hasPrevious=a.J;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.C;b.seekableStart=a.B;b.seekableEnd=a.u;b.duration=a.G;b.loadedTime=a.H;b.liveIngestionTime=a.A;return b},Z7=function(a,b){g.Q.call(this);
this.o=0;this.A=a;this.C=[];this.B=new Qva;this.w=this.u=null;this.H=(0,g.x)(this.AK,this);this.F=(0,g.x)(this.em,this);this.G=(0,g.x)(this.zK,this);this.J=(0,g.x)(this.LK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.bv,this),Ewa(this))):c=3;0!=c&&(b?this.bv(c):g.qo((0,g.x)(function(){this.bv(c)},this),0));
var d=Cwa();d&&Y7(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},$7=function(a){return new R7(a.A.getPlayerContextData())},Ewa=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.A.subscribe(b,g.Sa(this.yM,b),this))},a)},Fwa=function(a){(0,g.y)(a.C,function(b){this.A.unsubscribeByKey(b)},a);
a.C.length=0},a8=function(a,b){50>a.B.Sc()&&a.B.u.push(b)},c8=function(a,b,c){var d=$7(a);
U7(d,c);-1E3!=d.playerState&&(d.playerState=b);b8(a,d)},d8=function(a,b,c){a.A.sendMessage(b,c)},b8=function(a,b){Fwa(a);
a.A.setPlayerContextData(X7(b));Ewa(a)},Y7=function(a,b){a.w&&(a.w.removeUpdateListener(a.H),a.w.removeMediaListener(a.F),a.em(null));
a.w=b;a.w&&(i7("CP","Setting cast session: "+a.w.sessionId),a.w.addUpdateListener(a.H),a.w.addMediaListener(a.F),a.w.media.length&&a.em(a.w.media[0]))},Gwa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=$7(a);b.contentId!=d.videoId&&i7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;U7(d,a.u.getEstimatedTime());b8(a,d)}else i7("CP","No cast media video. Ignoring state update.")},e8=function(a,b,c){return(0,g.x)(function(d){this.Tb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Tb("Retrying "+b+" using MDx browser channel."),d8(this,b,c))},a)},f8=function(a,b,c){g.Q.call(this);
this.B=NaN;this.M=!1;this.G=this.F=this.H=this.J=NaN;this.V=[];this.A=this.C=this.w=this.Ra=this.o=null;this.T=a;this.V.push(g.ap(window,"beforeunload",(0,g.x)(this.uF,this)));this.u=[];this.Ra=new R7;this.R=b.id;this.o=Hwa(this,c);this.o.subscribe("handlerOpened",this.EK,this);this.o.subscribe("handlerClosed",this.BK,this);this.o.subscribe("handlerError",this.CK,this);this.o.subscribe("handlerMessage",this.DK,this);Uva(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Ra.videoId;
g.Yr()&&g.Wr("yt-remote-session-video-id",d)},this)},g8=function(a){i7("conn",a)},Hwa=function(a,b){return new c7(f7(a.T,"/bc"),b)},h8=function(a,b){a.P("proxyStateChange",b)},Iwa=function(a){a.B=g.qo((0,g.x)(function(){g8("Connecting timeout");
this.mj(1)},a),2E4)},i8=function(a){g.so(a.B);
a.B=NaN},j8=function(a){g.so(a.J);
a.J=NaN},Jwa=function(a){k8(a);
a.H=g.qo((0,g.x)(function(){l8(this,"getNowPlaying")},a),2E4)},k8=function(a){g.so(a.H);
a.H=NaN},Lwa=function(a,b){b&&(i8(a),j8(a));
b==(d7(a.o)&&isNaN(a.B))?b&&(h8(a,1),l8(a,"getSubtitlesTrack")):b?(a.xx()&&a.Ra.reset(),h8(a,1),l8(a,"getNowPlaying"),Kwa(a)):a.mj(1)},Mwa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Ra.videoId&&(g.A.isEmpty(b.params)?a.Ra.o=null:a.Ra.o=b.params,a.P("remotePlayerChange"))},Nwa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Ra.listId=b.params.listId||a.Ra.listId;W7(a.Ra,c,d);a.P("remoteQueueChange")},Pwa=function(a,b){b.params=b.params||{};
Nwa(a,b);Owa(a,b);a.P("autoplayDismissed")},Owa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
U7(a.Ra,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Ra.playerState&&(c=-1E3);a.Ra.playerState=c;c=Number(b.params.loadedTime);a.Ra.H=isNaN(c)?0:c;c=Number(b.params.duration);a.Ra.G=isNaN(c)?0:c;c=a.Ra;var d=Number(b.params.liveIngestionTime);c.A=d;c.w=isNaN(d)?!1:!0;c=a.Ra;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.Ra.playerState?Jwa(a):k8(a);a.P("remotePlayerChange")},Qwa=function(a,b){if(-1E3!=
a.Ra.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Ra.playerState=c;c=parseInt(b.params.currentTime,10);U7(a.Ra,isNaN(c)?0:c);a.P("remotePlayerChange")}},Rwa=function(a,b){var c="true"==b.params.muted;
a.Ra.volume=parseInt(b.params.volume,10);a.Ra.muted=c;a.P("remotePlayerChange")},Swa=function(a,b){a.C=b.params.videoId;
a.P("nowAutoplaying",parseInt(b.params.timeout,10))},Twa=function(a,b){var c="true"==b.params.hasNext;
a.Ra.J="true"==b.params.hasPrevious;a.Ra.hasNext=c;a.P("previousNextChange")},Kwa=function(a){g.so(a.G);
a.G=g.qo((0,g.x)(a.mj,a,1),864E5)},l8=function(a,b,c){c?g8("Sending: action="+b+", params="+g.rk(c)):g8("Sending: action="+b);
a.o.sendMessage(b,c)},m8=function(a){m7.call(this,"ScreenServiceProxy");
this.Fd=a;this.u=[];this.u.push(this.Fd.$_s("screenChange",(0,g.x)(this.BP,this)));this.u.push(this.Fd.$_s("onlineScreenChange",(0,g.x)(this.bM,this)))},Ywa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.M("MDX_CONFIG")||b;Qua();p6();n8||(n8=new e7(b?b.loungeApiHost:void 0),Yua()&&(n8.o="/api/loungedev"));o8||(o8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ia("yt.mdx.remote.deferredProxies_",o8,void 0));Uwa();var c=p8();if(!c){var d=new v7(n8);g.Ia("yt.mdx.remote.screenService_",d,void 0);c=p8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);ywa(a,d,function(m){m?q8()&&Q7(q8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){c6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ia("yt.mdx.remote.initialized_",!0,void 0),r8("Initializing: "+g.rk(b)),s8.push(g.xo("yt-remote-cast2-availability-change",function(){c6("yt-remote-receiver-availability-change")})),s8.push(g.xo("yt-remote-cast2-receiver-selected",function(){t8(null);
c6("yt-remote-auto-connect","cast-selector-receiver")})),s8.push(g.xo("yt-remote-cast2-receiver-resumed",function(){c6("yt-remote-receiver-resumed","cast-selector-receiver")})),s8.push(g.xo("yt-remote-cast2-session-change",Vwa)),s8.push(g.xo("yt-remote-connection-change",function(m){m?Q7(q8(),"YouTube TV"):u8()||(Q7(null,null),Bwa())})),a=v8(),b.isAuto&&(a.id+="#dial"),g.go("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),r8(" -- with channel params: "+
g.rk(a)),Wwa(a),c.start(),q8()||Xwa())},$wa=function(){var a=Zwa();
N7()&&g.Xr("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Zwa=function(){var a=p8().Fd.$_gos();
var b=w8();b&&x8()&&(j6(a,b)||a.push(b));return Pua(a)},y8=function(){var a=axa();
!a&&N7()&&Awa()&&(a={key:"cast-selector-receiver",name:Awa()});return a},axa=function(){var a=Zwa(),b=w8();
b||(b=u8());return g.Za(a,function(c){return b&&f6(b,c.key)?!0:!1})},w8=function(){var a=q8();
if(!a)return null;var b=p8().oe();return k6(b,a)},Vwa=function(a){r8("remote.onCastSessionChange_: "+g6(a));
if(a){var b=w8();b&&b.id==a.id?Q7(b.id,"YouTube TV"):(b&&z8(),A8(a,1))}else x8()&&z8()},z8=function(){O7()?L7().stopSession():J7("stopSession called before API ready.");
var a=x8();a&&(a.disconnect(1),B8(null))},C8=function(){var a=x8();
return!!a&&3!=a.getProxyState()},r8=function(a){i7("remote",a)},p8=function(){if(!D8){var a=g.w("yt.mdx.remote.screenService_");
D8=a?new m8(a):null}return D8},q8=function(){return g.w("yt.mdx.remote.currentScreenId_")},bxa=function(a){g.Ia("yt.mdx.remote.currentScreenId_",a,void 0)},cxa=function(){return g.w("yt.mdx.remote.connectData_")},t8=function(a){g.Ia("yt.mdx.remote.connectData_",a,void 0)},x8=function(){return g.w("yt.mdx.remote.connection_")},B8=function(a){var b=x8();
t8(null);a||bxa("");g.Ia("yt.mdx.remote.connection_",a,void 0);o8&&((0,g.y)(o8,function(c){c(a)}),o8.length=0);
b&&!a?c6("yt-remote-connection-change",!1):!b&&a&&c6("yt-remote-connection-change",!0)},u8=function(){var a=g.Yr();
if(!a)return null;var b=p8().oe();return k6(b,a)},A8=function(a,b){q8();
w8()&&w8();if(E8)F8=a;else{bxa(a.id);var c=new f8(n8,a,v8());c.connect(b,cxa());c.subscribe("beforeDisconnect",function(d){c6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){x8()&&(x8(),B8(null))});
B8(c)}},Xwa=function(){var a=u8();
a?(r8("Resume connection to: "+g6(a)),A8(a,0)):(q6(),Bwa(),r8("Skipping connecting because no session screen found."))},Uwa=function(){var a=v8();
if(g.A.isEmpty(a)){a=o6();var b=g.Xr("yt-remote-session-name")||"",c=g.Xr("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ia("yt.mdx.remote.channelParams_",a,void 0)}},v8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Wwa=function(a){a?(g.Wr("yt-remote-session-app",a.app),g.Wr("yt-remote-session-name",a.name)):(l6("yt-remote-session-app"),l6("yt-remote-session-name"));
g.Ia("yt.mdx.remote.channelParams_",a,void 0)},G8=function(a,b,c){g.B.call(this);
this.B=a;this.u=b;this.w=new g.P(this);g.C(this,this.w);this.w.L(b,"onCaptionsTrackListChanged",this.xL);this.w.L(b,"captionschanged",this.yK);this.w.L(b,"captionssettingschanged",this.jC);this.w.L(b,"videoplayerreset",this.zp);this.w.L(b,"mdxautoplaycancel",this.lE);this.R=this.w.L(b,"onVolumeChange",this.BA);this.G=!1;this.o=c;c.ga();c.subscribe("proxyStateChange",this.TA,this);c.subscribe("remotePlayerChange",this.nm,this);c.subscribe("remoteQueueChange",this.zp,this);c.subscribe("autoplayUpNext",
this.pA,this);c.subscribe("previousNextChange",this.PA,this);c.subscribe("nowAutoplaying",this.KA,this);c.subscribe("autoplayDismissed",this.oA,this);this.suggestion=null;this.H=new g.oC(64);this.A=new g.I(this.hC,500,this);g.C(this,this.A);this.C=new g.I(this.iC,1E3,this);g.C(this,this.C);this.M=new u6(this.dP,0,this);g.C(this,this.M);this.F={};this.V=new g.I(this.JC,1E3,this);g.C(this,this.V);this.J=new v6(this.jI,1E3,this);g.C(this,this.J);this.T=g.Ja;this.jC();this.zp();this.nm()},H8=function(a,
b){var c=a.B,d=a.u.getVideoData().lengthSeconds;
c.V=b||0;c.player.P("progresssync",b,d)},dxa=function(a){H8(a,0);
a.A.stop();I8(a,new g.oC(64))},K8=function(a,b){if(J8(a)&&!a.G){var c=null;
b&&(c={style:a.u.getSubtitlesUserSettings()},g.A.extend(c,b));a.o.YB(a.u.getVideoData(1).videoId,c);a.F=$7(a.o).o}},L8=function(a,b){var c=a.u.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.u.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.yf,Eua(c));I8(a,new g.oC(1))},exa=function(a,b){if(b){var c=a.u.getOption("captions","tracklist",{BT:1});
c&&c.length?(a.u.setOption("captions","track",b),a.G=!1):(a.u.loadModule("captions"),a.G=!0)}else a.u.setOption("captions","track",{})},J8=function(a){return $7(a.o).videoId==a.u.getVideoData(1).videoId},I8=function(a,b){a.C.stop();
var c=a.H;if(!g.uC(c,b)){var d=g.X(b,2);d!=g.X(a.H,2)&&g.gS(a.u.app,d);a.H=b;fxa(a.B,c,b)}},M8=function(){g.S.call(this,{D:"div",
I:"ytp-mdx-popup-dialog",N:{role:"dialog"},K:[{D:"div",I:"ytp-mdx-popup-dialog-inner-content",K:[{D:"div",I:"ytp-mdx-popup-title",W:"You're signed out"},{D:"div",I:"ytp-mdx-popup-description",W:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",I:"ytp-mdx-privacy-popup-buttons",K:[{D:"button",Y:["ytp-button","ytp-mdx-privacy-popup-cancel"],W:"Cancel"},{D:"button",Y:["ytp-button","ytp-mdx-privacy-popup-confirm"],
W:"Confirm"}]}]}]});this.u=new g.gL(this,250);g.C(this,this.u);this.C=this.o["ytp-mdx-privacy-popup-cancel"];this.L(this.C,"click",this.w);this.A=this.o["ytp-mdx-privacy-popup-confirm"];this.L(this.A,"click",this.B)},N8=function(a){g.S.call(this,{D:"div",
I:"ytp-remote",K:[{D:"div",I:"ytp-remote-display-status",K:[{D:"div",I:"ytp-remote-display-status-icon",K:[g.iL()]},{D:"div",I:"ytp-remote-display-status-text",W:"{{statustext}}"}]}]});this.u=new g.gL(this,250);g.C(this,this.u);this.w=a;this.L(a,"presentingplayerstatechange",this.A);gxa(this,g.hK(a))},gxa=function(a,b){if(3==a.w.getPresentingPlayerType()){var c={RECEIVER_NAME:a.w.getOption("remote","currentReceiver").name};
c=g.X(b,128)?g.ML("Error on $RECEIVER_NAME",c):b.ab()||g.X(b,4)?g.ML("Playing on $RECEIVER_NAME",c):g.ML("Connected to $RECEIVER_NAME",c);a.ia("statustext",c);a.u.show()}else a.u.hide()},O8=function(a,b){g.HN.call(this,"Play on",0,a,b);
this.u=a;this.C={};this.L(a,"onMdxReceiversChange",this.J);this.L(a,"presentingplayerstatechange",this.J);this.J()},P8=function(a){g.MK.call(this,a);
this.u={key:i6(),name:"This computer"};this.B=null;this.A=[];this.R=this.o=null;this.J=[this.u];this.w=this.u;this.F=new g.oC(64);this.V=0;this.H=-1;this.C=null;if(!g.Py(this.player.O())){a=this.player;var b=g.TB(a);b&&(b=b.Sl())&&(b=new O8(a,b),g.C(this,b));b=new N8(a);g.C(this,b);g.zK(a,b.element,4);this.C=new M8;g.C(this,this.C);g.zK(a,this.C.element,4);this.M=!!u8()}this.G=null},Q8=function(a){a.G&&(a.player.removeEventListener("presentingplayerstatechange",a.G),a.G=null)},fxa=function(a,b,c){a.F=
c;
a.player.P("presentingplayerstatechange",new g.zC(c,b))},R8=function(a,b){if(b.key!=a.w.key)if(b.key==a.u.key)z8();
else{var c;(c=!g.T(a.player.O().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.M("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.M("SESSION_INDEX")&&!g.M("LOGGED_IN")))||a.M||!a.C);if(c?0:g.Xy(a.player.O())||"WEB_EMBEDDED_PLAYER"==a.player.O().deviceParams.c)g.hK(a.player).ab()?a.player.pauseVideo():(a.G=(0,g.x)(a.XN,a),a.player.addEventListener("presentingplayerstatechange",a.G)),a.C&&a.C.Zb(),x8()||(E8=!0);a.w=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=
c.videoId;if(!d&&!e||(2==a.player.getAppState()||1==a.player.getAppState())&&g.T(a.player.O().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.wa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.yf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=Eua(c))&&(d.locationInfo=c);c=d}r8("Connecting to: "+
g.rk(b));"cast-selector-receiver"==b.key?(t8(c||null),c=c||null,O7()?L7().setLaunchParams(c):J7("setLaunchParams called before ready.")):!c&&C8()&&q8()==b.key?c6("yt-remote-connection-change",!0):(z8(),t8(c||null),c=p8().oe(),(c=k6(c,b.key))&&A8(c,1))}},nva={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},I6={"'":"\\'"},hxa={},Lua={eQ:"atp",LS:"ska",AS:"que",TR:"mus",KS:"sus",fR:"dsp",HS:"seq"};
d6.prototype.bi=function(){var a=new d6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.w=this.w;a.u=this.u;a.o=this.o};
d6.prototype.qb=function(a){return a?this.id==a.id:!1};
var r6,n6="",cva=Zua("loadCastFramework")||Zua("loadCastApplicationFramework"),xwa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ua(u6,g.B);g.h=u6.prototype;g.h.qF=function(a){this.A=arguments;this.o=!1;this.Ea?this.w=(0,g.H)()+this.Gd:this.Ea=g.zf(this.B,this.Gd)};
g.h.stop=function(){this.Ea&&(g.v.clearTimeout(this.Ea),this.Ea=null);this.w=null;this.o=!1;this.A=[]};
g.h.pause=function(){++this.u};
g.h.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.C.apply(null,this.A)))};
g.h.X=function(){this.stop();u6.Fb.X.call(this)};
g.h.rF=function(){this.w?(this.Ea=g.zf(this.B,this.w-(0,g.H)()),this.w=null):(this.Ea=null,this.u?this.o=!0:(this.o=!1,this.C.apply(null,this.A)))};g.Ua(v6,g.B);g.h=v6.prototype;g.h.vj=!1;g.h.jl=0;g.h.Ea=null;g.h.Fx=function(a){this.o=arguments;this.Ea||this.jl?this.vj=!0:w6(this)};
g.h.stop=function(){this.Ea&&(g.v.clearTimeout(this.Ea),this.Ea=null,this.vj=!1,this.o=[])};
g.h.pause=function(){this.jl++};
g.h.resume=function(){this.jl--;this.jl||!this.vj||this.Ea||(this.vj=!1,w6(this))};
g.h.X=function(){v6.Fb.X.call(this);this.stop()};
g.h.sF=function(){this.Ea=null;this.vj&&!this.jl&&(this.vj=!1,w6(this))};y6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};z6.prototype.o=null;z6.prototype.getOptions=function(){var a;(a=this.o)||(a={},gva(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var S8;g.Ua(fva,z6);S8=new fva;g.h=A6.prototype;g.h.oi=null;g.h.ff=!1;g.h.xk=null;g.h.Yu=null;g.h.fk=null;g.h.wj=null;g.h.Sg=null;g.h.Eh=null;g.h.Ni=null;g.h.Oc=null;g.h.Qm=0;g.h.kf=null;g.h.qq=null;g.h.hh=null;g.h.ll=-1;g.h.TB=!0;g.h.Vh=!1;g.h.Ur=0;g.h.Ip=null;var lva={},D6={};g.h=A6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.iO=function(a){a=a.target;var b=this.Ip;b&&3==R6(a)?b.Fx():this.RC(a)};
g.h.RC=function(a){try{if(a==this.Oc)a:{var b=R6(this.Oc),c=this.Oc.C,d=this.Oc.getStatus();if(g.Od&&!g.sd(10)||g.Qd&&!g.rd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.eh&&!T6(this.Oc))break a;this.Vh||4!=b||7==c||(8==c||0>=d?this.o.cf(3):this.o.cf(2));K6(this);var e=this.Oc.getStatus();this.ll=e;var f=T6(this.Oc);(this.ff=200==e)?(4==b&&G6(this),this.C?(mva(this,b,f),g.eh&&this.ff&&3==b&&(this.A.ka(this.u,"tick",this.bO),this.u.start())):F6(this,f),this.ff&&!this.Vh&&(4==b?this.o.wp(this):(this.ff=
!1,C6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.hh=3,E6(13)):(this.hh=0,E6(14)),G6(this),H6(this))}}catch(k){this.Oc&&T6(this.Oc)}finally{}};
g.h.bO=function(){var a=R6(this.Oc),b=T6(this.Oc);this.Qm<b.length&&(K6(this),mva(this,a,b),this.ff&&4!=a&&C6(this))};
g.h.DN=function(a){J6((0,g.x)(this.CN,this,a),0)};
g.h.CN=function(a){this.Vh||(K6(this),F6(this,a),C6(this))};
g.h.aB=function(a){J6((0,g.x)(this.BN,this,a),0)};
g.h.BN=function(a){this.Vh||(G6(this),this.ff=a,this.o.wp(this),this.o.cf(4))};
g.h.cancel=function(){this.Vh=!0;G6(this)};
g.h.LN=function(){this.xk=null;var a=(0,g.H)();0<=a-this.Yu?(2!=this.wj&&this.o.cf(3),G6(this),this.hh=2,E6(18),H6(this)):pva(this,this.Yu-a)};
g.h.getLastError=function(){return this.hh};g.h=sva.prototype;g.h.Sr=null;g.h.ae=null;g.h.Jp=!1;g.h.Hx=null;g.h.Wn=null;g.h.Fs=null;g.h.Tr=null;g.h.De=null;g.h.mg=-1;g.h.kl=null;g.h.Fk=null;g.h.connect=function(a){this.Tr=a;a=M6(this.o,null,this.Tr);E6(3);this.Hx=(0,g.H)();var b=this.o.G;null!=b?(this.kl=b[0],(this.Fk=b[1])?(this.De=1,tva(this)):(this.De=2,O6(this))):(a6(a,"MODE","init"),this.ae=new A6(this,void 0,void 0,void 0),this.ae.oi=this.Sr,B6(this.ae,a,!1,null,!0),this.De=0)};
g.h.mE=function(a){if(a)this.De=2,O6(this);else{E6(4);var b=this.o;b.wf=b.Wg.mg;$6(b,9)}a&&this.cf(2)};
g.h.ir=function(a){return this.o.ir(a)};
g.h.abort=function(){this.ae&&(this.ae.cancel(),this.ae=null);this.mg=-1};
g.h.Gx=function(){return!1};
g.h.UA=function(a,b){this.mg=a.ll;if(0==this.De)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.wf=this.mg;$6(c,2);return}this.kl=c[0];this.Fk=c[1]}else c=this.o,c.wf=this.mg,$6(c,2);else if(2==this.De)if(this.Jp)E6(7),this.Fs=(0,g.H)();else if("11111"==b){if(E6(6),this.Jp=!0,this.Wn=(0,g.H)(),c=this.Wn-this.Hx,!g.Od||g.sd(10)||500>c)this.mg=200,this.ae.cancel(),E6(12),N6(this.o,this,!0)}else E6(8),this.Wn=this.Fs=(0,g.H)(),this.Jp=!1};
g.h.wp=function(){this.mg=this.ae.ll;if(this.ae.ff)0==this.De?this.Fk?(this.De=1,tva(this)):(this.De=2,O6(this)):2==this.De&&((!g.Od||g.sd(10)?!this.Jp:200>this.Fs-this.Wn)?(E6(11),N6(this.o,this,!1)):(E6(12),N6(this.o,this,!0)));else{0==this.De?E6(9):2==this.De&&E6(10);var a=this.o;this.ae.getLastError();a.wf=this.mg;$6(a,2)}};
g.h.Em=function(){return this.o.Em()};
g.h.isActive=function(){return this.o.isActive()};
g.h.cf=function(a){this.o.cf(a)};g.Ua(P6,g.Ne);var yva=/^https?$/i,ixa=["POST","PUT"];g.h=P6.prototype;
g.h.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.H+"; newUri="+a);b=b?b.toUpperCase():"GET";this.H=a;this.A="";this.C=0;this.da=b;this.T=!1;this.w=!0;this.o=this.R?hva(this.R):hva(S8);this.V=this.R?this.R.getOptions():S8.getOptions();this.o.onreadystatechange=(0,g.x)(this.QA,this);try{b6(S6(this,"Opening Xhr")),this.aa=!0,this.o.open(b,String(a),!0),this.aa=!1}catch(f){b6(S6(this,"Error opening Xhr: "+f.message));xva(this,f);return}a=
c||"";var e=this.headers.clone();d&&g.um(d,function(f,k){e.set(k,f)});
d=g.Za(e.Gb(),vva);c=g.v.FormData&&a instanceof g.v.FormData;!g.bb(ixa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.o.setRequestHeader(k,f)},this);
this.ea&&(this.o.responseType=this.ea);"withCredentials"in this.o&&this.o.withCredentials!==this.Z&&(this.o.withCredentials=this.Z);try{Ava(this),0<this.F&&(this.M=uva(this.o),b6(S6(this,"Will abort after "+this.F+"ms if incomplete, xhr2 "+this.M)),this.M?(this.o.timeout=this.F,this.o.ontimeout=(0,g.x)(this.Ix,this)):this.J=g.zf(this.Ix,this.F,this)),b6(S6(this,"Sending request")),this.G=!0,this.o.send(a),this.G=!1}catch(f){b6(S6(this,"Send error: "+f.message)),xva(this,f)}};
g.h.Ix=function(){"undefined"!=typeof g.S1&&this.o&&(this.A="Timed out after "+this.F+"ms, aborting",this.C=8,S6(this,this.A),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.o&&this.w&&(S6(this,"Aborting"),this.w=!1,this.B=!0,this.o.abort(),this.B=!1,this.C=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Q6(this))};
g.h.X=function(){this.o&&(this.w&&(this.w=!1,this.B=!0,this.o.abort(),this.B=!1),Q6(this,!0));P6.Fb.X.call(this)};
g.h.QA=function(){this.ga()||(this.aa||this.G||this.B?zva(this):this.AM())};
g.h.AM=function(){zva(this)};
g.h.isActive=function(){return!!this.o};
g.h.getStatus=function(){try{return 2<R6(this)?this.o.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return"string"===typeof this.A?this.A:String(this.A)};g.h=U6.prototype;g.h.Tk=null;g.h.Sd=null;g.h.sc=null;g.h.Rr=null;g.h.Zn=null;g.h.ew=null;g.h.oo=null;g.h.cm=0;g.h.TJ=0;g.h.Cd=null;g.h.bh=null;g.h.Wf=null;g.h.di=null;g.h.Wg=null;g.h.nq=null;g.h.Ij=-1;g.h.py=-1;g.h.wf=-1;g.h.pj=0;g.h.fj=0;g.h.Wh=8;var a7=new g.Ne;g.Ua(Cva,g.pe);g.Ua(Dva,g.pe);g.Ua(Eva,g.pe);g.h=U6.prototype;g.h.connect=function(a,b,c,d,e){E6(0);this.Rr=b;this.Tk=c||{};d&&void 0!==e&&(this.Tk.OSID=d,this.Tk.OAID=e);this.C?(J6((0,g.x)(this.Aw,this,a),100),Iva(this)):this.Aw(a)};
g.h.Aw=function(a){this.Wg=new sva(this);this.Wg.Sr=null;this.Wg.u=this.B;this.Wg.connect(a)};
g.h.Gx=function(){return 0==this.o};
g.h.ZA=function(a){this.bh=null;Lva(this,a)};
g.h.YA=function(){this.Wf=null;this.sc=new A6(this,this.w,"rpc",this.F);this.sc.oi=null;this.sc.Ur=0;var a=this.ew.clone();Z5(a,"RID","rpc");Z5(a,"SID",this.w);Z5(a,"CI",this.nq?"0":"1");Z5(a,"AID",this.Ij);V6(this,a);if(!g.Od||g.sd(10))Z5(a,"TYPE","xmlhttp"),B6(this.sc,a,!0,this.oo,!1);else{Z5(a,"TYPE","html");var b=this.sc,c=!!this.oo;b.wj=3;b.Sg=$5(a.clone());ova(b,c)}};
g.h.UA=function(a,b){if(0!=this.o&&(this.sc==a||this.Sd==a))if(this.wf=a.ll,this.Sd==a&&3==this.o)if(7<this.Wh){try{var c=this.B.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Wf){if(this.sc)if(this.sc.fk+3E3<this.Sd.fk)X6(this),this.sc.cancel(),this.sc=null;else break a;Z6(this);E6(19)}}else this.py=c[1],0<this.py-this.Ij&&37500>c[2]&&this.nq&&0==this.fj&&!this.di&&(this.di=J6((0,g.x)(this.uK,this),6E3));else $6(this,11)}else b!=hxa.BQ.o&&$6(this,11);else if(this.sc==
a&&X6(this),!g.Lb(b)){c=this.B.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.Ij=e[0];e=e[1];2==this.o?"c"==e[0]?(this.w=e[1],this.oo=e[2],e=e[3],null!=e?this.Wh=e:this.Wh=6,this.o=3,this.Cd&&this.Cd.uw(),this.ew=M6(this,this.Em()?this.oo:null,this.Rr),Mva(this)):"stop"==e[0]&&$6(this,7):3==this.o&&("stop"==e[0]?$6(this,7):"noop"!=e[0]&&this.Cd&&this.Cd.tw(e),this.fj=0)}}};
g.h.uK=function(){null!=this.di&&(this.di=null,this.sc.cancel(),this.sc=null,Z6(this),E6(20))};
g.h.wp=function(a){if(this.sc==a){X6(this);this.sc=null;var b=2}else if(this.Sd==a)this.Sd=null,b=1;else return;this.wf=a.ll;if(0!=this.o)if(a.ff)1==b?(b=(0,g.H)()-a.fk,a7.dispatchEvent(new Dva(a7,a.Ni?a.Ni.length:0,b,this.pj)),W6(this),this.A.length=0):Mva(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.wf)){if(d=1==b)this.Sd||this.bh||1==this.o||2<=this.pj?d=!1:(this.bh=J6((0,g.x)(this.ZA,this,a),Nva(this,this.pj)),this.pj++,d=!0);d=!(d||2==b&&Z6(this))}if(d)switch(c){case 1:$6(this,
5);break;case 4:$6(this,10);break;case 3:$6(this,6);break;case 7:$6(this,12);break;default:$6(this,2)}}};
g.h.LE=function(a){if(!g.bb(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.UO=function(a){a?E6(2):(E6(1),Ova(this,8))};
g.h.ir=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new P6;a.Z=!1;return a};
g.h.isActive=function(){return!!this.Cd&&this.Cd.isActive(this)};
g.h.cf=function(a){a7.dispatchEvent(new Eva(a7,a))};
g.h.Em=function(){return!(!g.Od||g.sd(10))};
g.h=Pva.prototype;g.h.uw=function(){};
g.h.tw=function(){};
g.h.rw=function(){};
g.h.ar=function(){};
g.h.dx=function(){return{}};
g.h.isActive=function(){return!0};g.h=Qva.prototype;g.h.Sc=function(){return this.o.length+this.u.length};
g.h.isEmpty=function(){return g.cb(this.o)&&g.cb(this.u)};
g.h.clear=function(){this.o=[];this.u=[]};
g.h.contains=function(a){return g.bb(this.o,a)||g.bb(this.u,a)};
g.h.remove=function(a){var b=this.o;var c=(0,g.Hpa)(b,a);0<=c?(g.eb(b,c),b=!0):b=!1;return b||g.fb(this.u,a)};
g.h.tc=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Ua(b7,g.B);g.h=b7.prototype;g.h.uN=function(){this.Gd=Math.min(3E5,2*this.Gd);this.w();this.u&&this.start()};
g.h.start=function(){var a=this.Gd+15E3*Math.random();g.dn(this.o,a);this.u=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.u=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Gd=5E3};g.Ua(c7,Pva);g.h=c7.prototype;g.h.subscribe=function(a,b,c){return this.w.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.w.unsubscribe(a,b,c)};
g.h.wh=function(a){return this.w.ri(a)};
g.h.P=function(a,b){return this.w.P.apply(this.w,arguments)};
g.h.dispose=function(){this.vb||(this.vb=!0,g.ne(this.w),Tva(this),g.ne(this.u),this.u=null)};
g.h.ga=function(){return this.vb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.H="";this.u.stop();this.B=a||null;this.A=b||0;a=this.J+"/test";b=this.J+"/bind";var d=new U6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.o;e&&(e.Cd=null);d.Cd=this;this.o=d;e?this.o.connect(a,b,this.C,e.w,e.Ij):c?this.o.connect(a,b,this.C,c.sessionId,c.arrayId):this.o.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.A.extend(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.F.push(c):d7(this)&&Jva(this.o,c)};
g.h.uw=function(){this.u.reset();this.B=null;this.A=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)Jva(this.o,a[b])}this.P("handlerOpened")};
g.h.rw=function(a){var b=2==a&&401==this.o.wf;4==a||b||this.u.start();this.P("handlerError",a)};
g.h.ar=function(a){if(!this.u.isActive())this.P("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.dx=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.G&&(a.ui=""+this.G);this.B&&g.A.extend(a,this.B);return a};
g.h.tw=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),Hva(this.o)):this.P("handlerMessage",new Rva(a[0],a[1]))};
g.h.xO=function(){this.u.isActive();var a=this.o,b=0;a.sc&&b++;a.Sd&&b++;0==b&&this.connect(this.B,this.A)};e7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
e7.prototype.w=function(a,b){a(Error("Request error: "+b.status))};
e7.prototype.B=function(a){a(Error("request timed out"))};var awa=(0,g.H)(),h7=null,k7=Array(50),j7=-1,l7=!1;g.Ua(m7,g.Q);m7.prototype.oe=function(){return this.o};
m7.prototype.contains=function(a){return!!j6(this.o,a)};
m7.prototype.get=function(a){return a?k6(this.o,a):null};
m7.prototype.info=function(a){i7(this.F,a)};g.r(n7,g.Q);g.h=n7.prototype;g.h.start=function(){!this.o&&isNaN(this.Ea)&&this.WC()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ea)||(g.so(this.Ea),this.Ea=NaN)};
g.h.X=function(){this.stop();g.Q.prototype.X.call(this)};
g.h.WC=function(){this.Ea=NaN;this.o=g.$p(f7(this.C,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:this.A},timeout:5E3,onSuccess:(0,g.x)(this.zP,this),onError:(0,g.x)(this.yP,this),Yd:(0,g.x)(this.AP,this)})};
g.h.zP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.w;this.P("pairingComplete",new e6(c))};
g.h.yP=function(a){this.o=null;a.status&&404==a.status?this.u>=jxa.length?this.P("pairingFailed",Error("DIAL polling timed out")):(a=jxa[this.u],this.Ea=g.qo((0,g.x)(this.WC,this),a),this.u++):this.P("pairingFailed",Error("Server error "+a.status))};
g.h.AP=function(){this.o=null;this.P("pairingFailed",Error("Server not responding"))};
var jxa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ua(p7,m7);g.h=p7.prototype;g.h.start=function(){o7(this)&&this.P("screenChange");!g.Xr("yt-remote-lounge-token-expiration")&&ewa(this);g.so(this.u);this.u=g.qo((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){o7(this);bwa(this,a);q7(this,!1);this.P("screenChange");b(a);a.token||ewa(this)};
g.h.remove=function(a,b){var c=o7(this);dwa(this,a)&&(q7(this,!1),c=!0);b(a);c&&this.P("screenChange")};
g.h.lq=function(a,b,c,d){var e=o7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,q7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.P("screenChange")};
g.h.X=function(){g.so(this.u);p7.Fb.X.call(this)};
g.h.CF=function(a){o7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}q7(this,!b);b&&i7(this.F,"Missed "+b+" lounge tokens.")};
g.h.BF=function(a){i7(this.F,"Requesting lounge tokens failed: "+a)};g.r(s7,g.Q);g.h=s7.prototype;g.h.start=function(){var a=parseInt(g.Xr("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.H)()-144E5<a?0:a)?u7(this):(this.A=(0,g.H)()+3E5,g.Wr("yt-remote-fast-check-period",this.A),this.ou())};
g.h.isEmpty=function(){return g.A.isEmpty(this.o)};
g.h.update=function(){r7("Updating availability on schedule.");var a=this.C(),b=g.A.filter(this.o,function(c,d){return c&&!!k6(a,d)},this);
t7(this,b)};
g.h.X=function(){g.so(this.w);this.w=NaN;this.u&&(this.u.abort(),this.u=null);g.Q.prototype.X.call(this)};
g.h.ou=function(){g.so(this.w);this.w=NaN;this.u&&this.u.abort();var a=hwa(this);if(g.A.Sc(a)){var b=f7(this.B,"/pairing/get_screen_availability"),c={lounge_token:g.A.Gb(a).join(",")};this.u=g7(this.B,b,c,(0,g.x)(this.YM,this,a),(0,g.x)(this.XM,this))}else t7(this,{}),u7(this)};
g.h.YM=function(a,b){this.u=null;var c=g.A.Gb(hwa(this));if(g.tb(c,g.A.Gb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;t7(this,d);u7(this)}else this.Tb("Changing Screen set during request."),this.ou()};
g.h.XM=function(a){this.Tb("Screen availability failed: "+a);this.u=null;u7(this)};
g.h.Tb=function(a){i7("OnlineScreenService",a)};g.Ua(v7,m7);g.h=v7.prototype;g.h.start=function(){this.w.start();this.u.start();this.o.length&&(this.P("screenChange"),this.u.isEmpty()||this.P("onlineScreenChange"))};
g.h.add=function(a,b,c){this.w.add(a,b,c)};
g.h.remove=function(a,b,c){this.w.remove(a,b,c);this.u.update()};
g.h.lq=function(a,b,c,d){this.w.contains(a)?this.w.lq(a,b,c,d):(a="Updating name of unknown screen: "+a.name,i7(this.F,a),d(Error(a)))};
g.h.oe=function(a){return a?this.o:g.ib(this.o,(0,g.be)(this.A,function(b){return!this.contains(b)},this))};
g.h.XC=function(){return(0,g.be)(this.oe(!0),function(a){return!!this.u.o[a.id]},this)};
g.h.YC=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new n7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.ne(f);d(w7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.ne(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.CP=function(a,b,c,d){g.$p(f7(this.C,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new e6(f.screen||{});if(!k.name||lwa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);lwa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(w7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Yd:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.ne(this.w);g.ne(this.u);v7.Fb.X.call(this)};
g.h.LF=function(){mwa(this);this.P("screenChange");this.u.update()};
v7.prototype.dispose=v7.prototype.dispose;g.Ua(y7,g.Q);g.h=y7.prototype;g.h.yp=function(a){this.w=a;this.P("sessionScreen",this.w)};
g.h.re=function(a){this.ga()||(a&&z7(this,""+a),this.w=null,this.P("sessionScreen",null))};
g.h.info=function(a){i7(this.V,a)};
g.h.aD=function(){return null};
g.h.yu=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){z7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.yu("");y7.Fb.X.call(this)};g.Ua(A7,y7);g.h=A7.prototype;g.h.xu=function(a){if(this.o){if(this.o==a)return;z7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.C);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.o=a;this.o.addUpdateListener(this.C);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);owa(this)};
g.h.Jj=function(a){this.info("launchWithParams no-op for Cast: "+g.rk(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.x)(function(){this.re()},this),(0,g.x)(function(){this.re(Error("Failed to stop receiver app."))},this)):this.re(Error("Stopping cast device witout session."))};
g.h.yu=g.Ja;g.h.X=function(){this.info("disposeInternal");g.so(this.A);this.A=0;this.o&&(this.o.removeUpdateListener(this.C),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.o=null;A7.Fb.X.call(this)};
g.h.TN=function(a,b){if(!this.ga())if(b){var c=x6(b);if(g.Pa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.rk(c));switch(d){case "mdxSessionStatus":nwa(this,c.screenId);break;default:z7(this,"Unknown youtube message: "+d)}}else z7(this,"Unable to parse message.")}else z7(this,"No data in message.")};
g.h.zx=function(a,b,c,d){kwa(this.H,this.u.label,a,this.u.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(z7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.qo((0,g.x)(this.zx,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.aD=function(){return this.o};
g.h.DP=function(a){this.ga()||a||(z7(this,"Cast session died."),this.re())};g.Ua(B7,y7);g.h=B7.prototype;g.h.xu=function(a){this.A=a;this.A.addUpdateListener(this.M)};
g.h.Jj=function(a){this.B=a;this.F()};
g.h.stop=function(){this.o();this.o=g.Ja;g.so(this.C);this.A?this.A.stop((0,g.x)(this.re,this,null),(0,g.x)(this.re,this,"Failed to stop DIAL device.")):this.re()};
g.h.X=function(){this.o();this.o=g.Ja;g.so(this.C);this.A&&this.A.removeUpdateListener(this.M);this.A=null;B7.Fb.X.call(this)};
g.h.GP=function(a){this.ga()||a||(z7(this,"DIAL session died."),this.o(),this.o=g.Ja,this.re())};
g.h.hs=function(a){this.J=i6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,qwa(this));a(b);pwa(this)}else this.F=(0,g.x)(function(){g.so(this.C);this.F=g.Ja;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,qwa(this));a(c);pwa(this)},this),this.C=g.qo((0,g.x)(function(){this.F()},this),100)};
g.h.eG=function(a,b,c){kwa(this.H,this.G.receiver.label,a,this.u.friendlyName,(0,g.x)(function(d){d&&d.token?(this.yp(d),b(new chrome.cast.DialLaunchResponse(!1))):this.hs(b,c)},this),(0,g.x)(function(d){z7(this,"Failed to get DIAL screen: "+d);
this.hs(b,c)},this))};g.Ua(C7,y7);C7.prototype.stop=function(){this.re()};
C7.prototype.xu=g.Ja;C7.prototype.Jj=function(){g.so(this.o);this.o=NaN;var a=k6(this.H.oe(),this.u.label);a?this.yp(a):this.re(Error("No such screen"))};
C7.prototype.X=function(){g.so(this.o);this.o=NaN;C7.Fb.X.call(this)};g.Ua(D7,g.Q);g.h=D7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.FM,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.WA,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.TK,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ga()||
(chrome.cast.addReceiverActionListener(this.A),Yva(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.ZC,this)),this.w=swa(this),chrome.cast.setCustomReceivers(this.w,g.Ja,(0,g.x)(function(k){this.Tb("Failed to set initial custom receivers: "+g.rk(k))},this)),this.P("yt-remote-cast2-availability-change",F7(this)),b(!0))},this),(0,g.x)(function(k){this.Tb("Failed to initialize API: "+g.rk(k));
b(!1)},this))};
g.h.FO=function(a,b){E7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.w;if(!a||c&&c.id!=a)E7("Unsetting old screen status: "+this.o.u.friendlyName),G7(this,null)}if(a&&b){if(!this.o){c=k6(this.u.oe(),a);if(!c){E7("setConnectedScreenStatus: Unknown screen.");return}var d=rwa(this,c);d||(E7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.w.push(d),chrome.cast.setCustomReceivers(this.w,
g.Ja,(0,g.x)(function(e){this.Tb("Failed to set initial custom receivers: "+g.rk(e))},this)));
E7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);G7(this,new C7(this.u,d),!0)}this.o.yu(b)}else E7("setConnectedScreenStatus: no screen.")};
g.h.GO=function(a){this.ga()?this.Tb("Setting connection data on disposed cast v2"):this.o?this.o.Jj(a):this.Tb("Setting connection data without a session")};
g.h.FP=function(){this.ga()?this.Tb("Stopping session on disposed cast v2"):this.o?(this.o.stop(),G7(this,null)):E7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.WA,this),(0,g.x)(this.cN,this))};
g.h.X=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.ZC,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.A);var a=Vva,b=g.w("yt.mdx.remote.debug.handlers_");g.fb(b||[],a);g.ne(this.o);D7.Fb.X.call(this)};
g.h.Tb=function(a){i7("Controller",a)};
g.h.XA=function(a,b){this.o==a&&(b||G7(this,null),this.P("yt-remote-cast2-session-change",b))};
g.h.BM=function(a,b){if(!this.ga())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),E7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.u.label!=a.label)E7("onReceiverAction_: Stopping active receiver: "+this.o.u.friendlyName),this.o.stop();else{E7("onReceiverAction_: Casting to active receiver.");this.o.w&&this.P("yt-remote-cast2-session-change",this.o.w);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:G7(this,
new C7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:G7(this,new B7(this.u,a,this.C));break;case chrome.cast.ReceiverType.CAST:G7(this,new A7(this.u,a));break;default:this.Tb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.u.label==a.label?this.o.stop():this.Tb("Stopping receiver w/o session: "+a.friendlyName)}else this.Tb("onReceiverAction_ called without receiver.")};
g.h.TK=function(a){if(this.ga())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Tb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.u:null;if(!c||c.label!=b.label)return this.Tb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.w)return E7("Reselecting dial screen."),
this.P("yt-remote-cast2-session-change",this.o.w),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Tb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);G7(this,new B7(this.u,b,this.C))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.eG,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.hs,b))};
g.h.WA=function(a){if(!this.ga()){E7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)E7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),G7(this,new A7(this.u,b),!0);else{this.Tb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.u,d=k6(this.u.oe(),c.label);d&&f6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(E7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.ne(this.o),this.o=new A7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.XA,this,this.o)),this.o.Jj(null));this.o.xu(a)}}};
g.h.EP=function(){return this.o?this.o.aD():null};
g.h.cN=function(a){this.ga()||(this.Tb("Failed to estabilish a session: "+g.rk(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&G7(this,null))};
g.h.FM=function(a){E7("Receiver availability updated: "+a);if(!this.ga()){var b=F7(this);this.B=a==chrome.cast.ReceiverAvailability.AVAILABLE;F7(this)!=b&&this.P("yt-remote-cast2-availability-change",F7(this))}};
g.h.ZC=function(){this.ga()||(this.w=swa(this),E7("Updating custom receivers: "+g.rk(this.w)),chrome.cast.setCustomReceivers(this.w,g.Ja,(0,g.x)(function(){this.Tb("Failed to set custom receivers.")},this)),this.P("yt-remote-cast2-availability-change",F7(this)))};
D7.prototype.setLaunchParams=D7.prototype.GO;D7.prototype.setConnectedScreenStatus=D7.prototype.FO;D7.prototype.stopSession=D7.prototype.FP;D7.prototype.getCastSession=D7.prototype.EP;D7.prototype.requestSession=D7.prototype.requestSession;D7.prototype.init=D7.prototype.init;D7.prototype.dispose=D7.prototype.dispose;var M7=[];g.h=R7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";S7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.J=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.C=a.playerTimeAt,this.B=a.seekableStart,this.u=a.seekableEnd,this.G=a.duration,this.H=a.loadedTime,this.A=a.liveIngestionTime,this.w=!isNaN(this.A))};
g.h.ab=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.w?this.G+T7(this):this.G};
g.h.clone=function(){return new R7(X7(this))};g.r(Z7,g.Q);g.h=Z7.prototype;g.h.play=function(){1==this.o?(this.u?this.u.play(null,g.Ja,e8(this,"play")):d8(this,"play"),c8(this,1,V7($7(this))),this.P("remotePlayerChange")):a8(this,this.play)};
g.h.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ja,e8(this,"pause")):d8(this,"pause"),c8(this,2,V7($7(this))),this.P("remotePlayerChange")):a8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.u){var b=$7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.ab()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ja,e8(this,"seekTo",{newTime:a}))}else d8(this,"seekTo",{newTime:a});c8(this,3,a);this.P("remotePlayerChange")}else a8(this,g.Sa(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ja,e8(this,"stopVideo")):d8(this,"stopVideo");var a=$7(this);a.index=-1;a.videoId="";S7(a);b8(this,a);this.P("remotePlayerChange")}else a8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=$7(this);if(this.w){if(c.volume!=a){var d=Math.round(a)/100;this.w.setReceiverVolumeLevel(d,(0,g.x)(function(){i7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Tb("failed to set receiver volume.")},this))}c.muted!=b&&this.w.setReceiverMuted(b,(0,g.x)(function(){i7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Tb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);d8(this,"setVolume",e)}c.muted=b;c.volume=a;b8(this,c)}else a8(this,g.Sa(this.setVolume,a,b))};
g.h.YB=function(a,b){if(1==this.o){var c=$7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.rk(b.style),g.A.extend(d,c.o));d8(this,"setSubtitlesTrack",d);b8(this,c)}else a8(this,g.Sa(this.YB,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();d8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=$7(this);d.audioTrackId=c;b8(this,d)}else a8(this,g.Sa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=$7(this);c=c||0;var m={videoId:a,currentIndex:c};W7(l,a,c);void 0!==b&&(U7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.rk(k));d8(this,"setPlaylist",m);d||b8(this,l)};
g.h.VC=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"previous")}else a8(this,g.Sa(this.VC,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"next")}else a8(this,g.Sa(this.nextVideo,a,b))};
g.h.Jw=function(){1==this.o?d8(this,"dismissAutoplay"):a8(this,this.Jw)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.P("proxyStateChange",a,this.o)}g.Q.prototype.dispose.call(this)};
g.h.X=function(){Fwa(this);this.A=null;this.B.clear();Y7(this,null);g.Q.prototype.X.call(this)};
g.h.bv=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.P("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.cb(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.h.yM=function(a,b){this.P(a,b)};
g.h.AK=function(a){if(!a)this.em(null),Y7(this,null);else if(this.w.receiver.volume){a=this.w.receiver.volume;var b=$7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)i7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,b8(this,b)}};
g.h.em=function(a){i7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.G);if(this.u=a)this.u.addUpdateListener(this.G),Gwa(this),this.P("remotePlayerChange")};
g.h.zK=function(a){a?(Gwa(this),this.P("remotePlayerChange")):this.em(null)};
g.h.LK=function(){var a=Cwa();a&&Y7(this,a)};
g.h.Tb=function(a){i7("CP",a)};g.r(f8,g.Q);g.h=f8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==k&&(l.currentIndex=k);c&&(this.Ra.listId=c);this.Ra.videoId=d;this.Ra.index=k||0;this.Ra.state=3;U7(this.Ra,m);this.A="UNSUPPORTED";g8("Connecting with setPlaylist and params: "+g.rk(l));this.o.connect({method:"setPlaylist",
params:g.rk(l)},a,Tua())}else g8("Connecting without params"),this.o.connect({},a,Tua());Iwa(this)};
g.h.dispose=function(){this.ga()||(this.P("beforeDispose"),h8(this,3));g.Q.prototype.dispose.call(this)};
g.h.X=function(){i8(this);k8(this);j8(this);g.so(this.F);this.F=NaN;g.so(this.G);this.G=NaN;this.w=null;g.bp(this.V);this.V.length=0;this.o.dispose();g.Q.prototype.X.call(this);this.A=this.C=this.u=this.Ra=this.o=null};
g.h.uF=function(){this.mj(2)};
g.h.EK=function(){g8("Channel opened");this.M&&(this.M=!1,j8(this),this.J=g.qo((0,g.x)(function(){g8("Timing out waiting for a screen.");this.mj(1)},this),15E3));
Xua(Sva(this.o),this.R)};
g.h.BK=function(){g8("Channel closed");isNaN(this.B)?q6(!0):q6();this.dispose()};
g.h.CK=function(a){q6();isNaN(this.al())?(g8("Channel error: "+a+" without reconnection"),this.dispose()):(this.M=!0,g8("Channel error: "+a+" with reconnection in "+this.al()+" ms"),h8(this,2))};
g.h.DK=function(a){a.params?g8("Received: action="+a.action+", params="+g.rk(a.params)):g8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=x6(a.params.devices);this.u=(0,g.ic)(a,function(c){return new d6(c)});
a=!!g.Za(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
Lwa(this,a);break;case "loungeScreenDisconnected":g.gb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
Lwa(this,!1);break;case "remoteConnected":var b=new d6(x6(a.params.device));g.Za(this.u,function(c){return c.qb(b)})||Fua(this.u,b);
break;case "remoteDisconnected":b=new d6(x6(a.params.device));g.gb(this.u,function(c){return c.qb(b)});
break;case "gracefulDisconnect":break;case "playlistModified":Nwa(this,a);break;case "nowPlaying":Pwa(this,a);break;case "onStateChange":Owa(this,a);break;case "onAdStateChange":Qwa(this,a);break;case "onVolumeChanged":Rwa(this,a);break;case "onSubtitlesTrackChanged":Mwa(this,a);break;case "nowAutoplaying":Swa(this,a);break;case "autoplayDismissed":this.P("autoplayDismissed");break;case "autoplayUpNext":this.C=a.params.videoId||null;this.P("autoplayUpNext",this.C);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.P("autoplayModeChange",this.A);"DISABLED"==this.A&&this.P("autoplayDismissed");break;case "onHasPreviousNextChanged":Twa(this,a);break;case "requestAssistedSignIn":this.P("assistedSignInRequested",a.params.authCode);break;default:g8("Unrecognized action: "+a.action)}};
g.h.tO=function(){if(this.w){var a=this.w;this.w=null;this.Ra.videoId!=a&&l8(this,"getNowPlaying")}};
g.h.jF=function(){var a=3;this.ga()||(a=0,isNaN(this.al())?d7(this.o)&&isNaN(this.B)&&(a=1):a=2);return a};
g.h.mj=function(a){g8("Disconnecting with "+a);i8(this);this.P("beforeDisconnect",a);1==a&&q6();Tva(this.o,a);this.dispose()};
g.h.iF=function(){var a=this.Ra;this.w&&(a=this.Ra.clone(),W7(a,this.w,a.index));return X7(a)};
g.h.HO=function(a){var b=new R7(a);b.videoId&&b.videoId!=this.Ra.videoId&&(this.w=b.videoId,g.so(this.F),this.F=g.qo((0,g.x)(this.tO,this),5E3));var c=[];this.Ra.listId==b.listId&&this.Ra.videoId==b.videoId&&this.Ra.index==b.index||c.push("remoteQueueChange");this.Ra.playerState==b.playerState&&this.Ra.volume==b.volume&&this.Ra.muted==b.muted&&V7(this.Ra)==V7(b)&&g.rk(this.Ra.o)==g.rk(b.o)||c.push("remotePlayerChange");this.Ra.reset(a);(0,g.y)(c,function(d){this.P(d)},this)};
g.h.xx=function(){var a=this.o.C.id,b=g.Za(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.al=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.H)():NaN};
g.h.XE=function(){return this.A||"UNSUPPORTED"};
g.h.YE=function(){return this.C||""};
g.h.xP=function(){if(!isNaN(this.al())){var a=this.o.u;g.en(a.o);a.start()}};
g.h.CO=function(a,b){l8(this,a,b);Kwa(this)};
f8.prototype.subscribe=f8.prototype.subscribe;f8.prototype.unsubscribeByKey=f8.prototype.wh;f8.prototype.getProxyState=f8.prototype.jF;f8.prototype.disconnect=f8.prototype.mj;f8.prototype.getPlayerContextData=f8.prototype.iF;f8.prototype.setPlayerContextData=f8.prototype.HO;f8.prototype.getOtherConnectedRemoteId=f8.prototype.xx;f8.prototype.getReconnectTimeout=f8.prototype.al;f8.prototype.getAutoplayMode=f8.prototype.XE;f8.prototype.getAutoplayVideoId=f8.prototype.YE;f8.prototype.reconnect=f8.prototype.xP;
f8.prototype.sendMessage=f8.prototype.CO;g.r(m8,m7);g.h=m8.prototype;g.h.oe=function(a){return this.Fd.$_gs(a)};
g.h.contains=function(a){return!!this.Fd.$_c(a)};
g.h.get=function(a){return this.Fd.$_g(a)};
g.h.start=function(){this.Fd.$_st()};
g.h.add=function(a,b,c){this.Fd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Fd.$_r(a,b,c)};
g.h.lq=function(a,b,c,d){this.Fd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.u.length;a<b;++a)this.Fd.$_ubk(this.u[a]);this.u.length=0;this.Fd=null;m7.prototype.X.call(this)};
g.h.BP=function(){this.P("screenChange")};
g.h.bM=function(){this.P("onlineScreenChange")};
v7.prototype.$_st=v7.prototype.start;v7.prototype.$_gspc=v7.prototype.CP;v7.prototype.$_gsppc=v7.prototype.YC;v7.prototype.$_c=v7.prototype.contains;v7.prototype.$_g=v7.prototype.get;v7.prototype.$_a=v7.prototype.add;v7.prototype.$_un=v7.prototype.lq;v7.prototype.$_r=v7.prototype.remove;v7.prototype.$_gs=v7.prototype.oe;v7.prototype.$_gos=v7.prototype.XC;v7.prototype.$_s=v7.prototype.subscribe;v7.prototype.$_ubk=v7.prototype.wh;var F8=null,E8=!1,n8=null,o8=null,D8=null,s8=[];g.r(G8,g.B);g.h=G8.prototype;
g.h.X=function(){g.B.prototype.X.call(this);this.A.stop();this.C.stop();this.M.stop();this.T();this.o.unsubscribe("proxyStateChange",this.TA,this);this.o.unsubscribe("remotePlayerChange",this.nm,this);this.o.unsubscribe("remoteQueueChange",this.zp,this);this.o.unsubscribe("autoplayUpNext",this.pA,this);this.o.unsubscribe("previousNextChange",this.PA,this);this.o.unsubscribe("nowAutoplaying",this.KA,this);this.o.unsubscribe("autoplayDismissed",this.oA,this);this.o=this.B=null};
g.h.mz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(J8(this)){if(!$7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":$7(this.o).ab()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.J.Fx(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.u.getCurrentTime();L8(this,0==c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,c)}};
g.h.yK=function(a){this.M.qF(a)};
g.h.dP=function(a){this.mz("control_subtitles_set_track",g.A.isEmpty(a)?null:a)};
g.h.jC=function(){var a=this.u.getOption("captions","track");g.A.isEmpty(a)||K8(this,a)};
g.h.BA=function(a){if(J8(this)){this.o.unsubscribe("remotePlayerChange",this.nm,this);var b=Math.round(a.volume);a=!!a.muted;var c=$7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.V.start();this.o.subscribe("remotePlayerChange",this.nm,this)}};
g.h.xL=function(){g.A.isEmpty(this.F)||exa(this,this.F);this.G=!1};
g.h.TA=function(a,b){this.C.stop();2==b&&this.iC()};
g.h.nm=function(){if(J8(this)){this.A.stop();var a=$7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.H=1;break;case 1082:case 1083:this.B.H=0;break;default:this.B.H=-1}switch(a.playerState){case 1081:case 1:I8(this,new g.oC(8));this.hC();break;case 1085:case 3:I8(this,new g.oC(9));break;case 1083:case 0:I8(this,new g.oC(2));this.J.stop();H8(this,this.u.getVideoData().lengthSeconds);break;case 1084:I8(this,new g.oC(4));break;case 2:I8(this,new g.oC(4));H8(this,V7(a));
break;case -1:I8(this,new g.oC(64));break;case -1E3:I8(this,new g.oC(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=$7(this.o).o;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.F=a,exa(this,a));a=$7(this.o);-1==a.volume||Math.round(this.u.getVolume())==a.volume&&this.u.isMuted()==a.muted||this.V.isActive()||this.JC()}else dxa(this)};
g.h.PA=function(){this.u.P("mdxpreviousnextchange")};
g.h.zp=function(){J8(this)||dxa(this)};
g.h.lE=function(){this.o.Jw()};
g.h.pA=function(){};
g.h.KA=function(a){isNaN(a)||this.u.P("mdxnowautoplaying",a)};
g.h.oA=function(){this.u.P("mdxautoplaycanceled")};
g.h.jI=function(a,b){-1==$7(this.o).playerState?L8(this,a):b&&this.o.seekTo(a)};
g.h.JC=function(){if(J8(this)){var a=$7(this.o);this.w.Va(this.R);a.muted?this.u.mute():this.u.unMute();this.u.setVolume(a.volume);this.R=this.w.L(this.u,"onVolumeChange",this.BA)}};
g.h.hC=function(){this.A.stop();if(!this.o.ga()){var a=$7(this.o);a.ab()&&I8(this,new g.oC(8));H8(this,V7(a));this.A.start()}};
g.h.iC=function(){this.C.stop();this.A.stop();var a=this.o.A.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.C.start()};g.r(M8,g.S);M8.prototype.Zb=function(){this.u.show()};
M8.prototype.w=function(){c6("mdx-privacy-popup-cancel");this.u.hide()};
M8.prototype.B=function(){c6("mdx-privacy-popup-confirm");this.u.hide()};g.r(N8,g.S);N8.prototype.A=function(a){gxa(this,a.state)};g.r(O8,g.HN);O8.prototype.J=function(){var a=this.u.getOption("remote","receivers");a&&1<a.length&&!this.u.getOption("remote","quickCast")?(this.C=g.vb(a,this.B,this),g.JN(this,(0,g.ic)(a,this.B)),a=this.u.getOption("remote","currentReceiver"),this.He(this.B(a)),this.enable(!0)):this.enable(!1)};
O8.prototype.B=function(a){return a.key};
O8.prototype.af=function(a){return"cast-selector-receiver"==a?"Cast...":this.C[a].name};
O8.prototype.ld=function(a){g.HN.prototype.ld.call(this,a);this.u.setOption("remote","currentReceiver",this.C[a]);this.w.Ya()};g.r(P8,g.MK);g.h=P8.prototype;
g.h.create=function(){Ywa(g.Gy(this.player.O()));this.A.push(g.xo("yt-remote-before-disconnect",this.vK,this));this.A.push(g.xo("yt-remote-connection-change",this.GM,this));this.A.push(g.xo("yt-remote-receiver-availability-change",this.RA,this));this.A.push(g.xo("yt-remote-auto-connect",this.EM,this));this.A.push(g.xo("yt-remote-receiver-resumed",this.DM,this));this.A.push(g.xo("mdx-privacy-popup-confirm",this.fO,this));this.A.push(g.xo("mdx-privacy-popup-cancel",this.eO,this));this.RA()};
g.h.load=function(){this.player.cancelPlayback();g.MK.prototype.load.call(this);this.B=new G8(this,this.player,this.o);var a=(a=cxa())?a.currentTime:0;var b=C8()?new Z7(x8(),void 0):null;0==a&&b&&(a=V7($7(b)));0!=a&&(this.V=a||0,this.player.P("progresssync",a,void 0));fxa(this,this.F,this.F);g.nS(this.player.app,6)};
g.h.unload=function(){this.player.P("mdxautoplaycanceled");this.w=this.u;g.oe(this.B,this.o);this.o=this.B=null;g.MK.prototype.unload.call(this);g.nS(this.player.app,5);Q8(this)};
g.h.X=function(){g.yo(this.A);g.MK.prototype.X.call(this)};
g.h.Kl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.mz.apply(this.B,[a].concat(g.na(c)))};
g.h.getAdState=function(){return this.H};
g.h.lF=function(){return this.loaded?this.B.suggestion:null};
g.h.Ly=function(){return this.o?$7(this.o).J:!1};
g.h.hasNext=function(){return this.o?$7(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.V};
g.h.getProgressState=function(){var a=$7(this.o),b=this.player.getVideoData();return{allowSeeking:g.T(this.player.O().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Tc():!a.isAdPlaying()&&this.player.Tc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.w?a.A+T7(a):a.A,isAtLiveHead:1>=(a.w?a.u+T7(a):a.u)-this.getCurrentTime(),loaded:a.H,seekableEnd:a.w?a.u+T7(a):a.u,seekableStart:0<a.B?a.B+T7(a):
a.B}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.FG=function(){this.o&&this.o.VC()};
g.h.vK=function(a){1==a&&(this.R=this.o?$7(this.o):null)};
g.h.GM=function(){var a=C8()?new Z7(x8(),void 0):null;if(a){var b=this.w;this.loaded&&this.unload();this.o=a;this.R=null;b.key!=this.u.key&&(this.w=b,this.load())}else g.ne(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.R)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,V7(a)));this.player.P("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.RA=function(){this.J=[this.u].concat($wa());var a=y8()||this.u;R8(this,a);this.player.ma("onMdxReceiversChange")};
g.h.XN=function(a){!this.M&&g.BC(a,8)&&(this.player.pauseVideo(),Q8(this))};
g.h.EM=function(){var a=y8();R8(this,a)};
g.h.DM=function(){this.w=y8()};
g.h.fO=function(){this.M=!0;Q8(this);E8=!1;F8&&A8(F8,1);F8=null};
g.h.eO=function(){this.M=!1;Q8(this);R8(this,this.u);this.w=this.u;E8=!1;F8=null;this.player.playVideo()};
g.h.Qc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.J;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?P7():R8(this,b)),this.loaded?this.w:this.u;case "quickCast":return 2==this.J.length&&"cast-selector-receiver"==this.J[1].key?(b&&P7(),!0):!1}};
g.h.GG=function(){d8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Qf=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.aL.remote=P8;})(_yt_player);
